# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "github-webhook"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"


plugins:
  Github::Webhook:
    secret: '|8MVY)<[2Zh@=<NSoCBBtb#LTQ6Ty0dlA*4s'
